# Generated by Django 5.1.4 on 2025-02-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('creator', 'title'), name='unique_title_per_user'),
        ),
    ]
