# Generated by Django 5.1.4 on 2025-02-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
    ]
