# Generated by Django 5.1.4 on 2025-02-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_date_listing_create_date_listing_close_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='author',
        ),
    ]
